import fs from 'node:fs/promises';
import path from 'node:path';
import { ConducksAdjacencyList } from '@/lib/core/graph/adjacency-list.js';
import { DAACClustering } from '@/lib/core/algorithms/clustering/daac.js';
import { ConfigDetector } from './config-detector.js';
import { ConducksSentinel } from './sentinel.js';
import { ConducksComponent } from "@/contracts/types.js";

export interface BlueprintDiff {
  nodesAdded: string[];
  nodesRemoved: string[];
  rankViolationsAdded: string[];
  rankViolationsRemoved: string[];
  newCycles: string[][];
  resolvedCycles: string[][];
}

/**
 * Conducks — Blueprint (AI-Readiness Generator)
 */
export class BlueprintGenerator implements ConducksComponent {
  public readonly id = 'blueprint-generator';
  public readonly type = 'analyzer';
  public readonly description = 'Generates high-fidelity project manifests for structural intelligence and GEO.';
  private daac = new DAACClustering();
  private detector = new ConfigDetector();
  private sentinel = new ConducksSentinel();

  /**
   * Generates a BLUEPRINT.md that summarizes the codebase 
   * based on the current graph and clusters.
   */
  public async generate(graph: ConducksAdjacencyList, outputDir: string = process.cwd()): Promise<string> {
    const clusterMap = this.daac.cluster(graph);
    const stats = graph.stats;
    
    // 1. Deep Discovery (Configs & Entry Points)
    const infra = await this.detector.discover(outputDir);
    
    // 2. Governance Audit
    const sentinelConfigPath = new URL('../../../../config/sentinel.json', import.meta.url);
    let sentinelRules: any[];
    try {
      sentinelRules = JSON.parse(await fs.readFile(sentinelConfigPath, 'utf-8').catch(() => '[]'));
    } catch {
      sentinelRules = [];
    }
    const audit = await this.sentinel.validate(graph, sentinelRules);

    // 3. Group by Clusters
    const clusters = new Map<string, string[]>();
    for (const [file, clusterId] of clusterMap.entries()) {
      if (!clusters.has(clusterId)) clusters.set(clusterId, []);
      clusters.get(clusterId)!.push(file);
    }

    let blueprint = `
# Conducks — Structural Graph Blueprint
This file provides a high-fidelity structural summary for AI agents and LLMs. 
Generated by the Conducks Graph on ${new Date().toLocaleString()}.

## 📊 Core Stats
- **Total Symbols (Nodes)**: ${stats.nodeCount}
- **Structural Relationships (Edges)**: ${stats.edgeCount}
- **Functional Modules**: ${clusters.size}

## 🏗️ Functional Architecture (DAAC Clusters)
The Conducks Graph has automatically categorized the following cohesive modules:

`;

    for (const [clusterId, files] of clusters.entries()) {
      const mainFiles = files.slice(0, 5).map(f => path.basename(f)).join(', ');
      blueprint += `### Module: ${clusterId}\n- **Core Files**: ${files.length} (${mainFiles}...)\n- **Context**: Structural cluster based on call-density and directory proximity.\n\n`;
    }

    blueprint += `
## 🚦 Entry Points & Config
Project root discovery found the following critical start points:
${infra.entries.map(e => `- Entry: ${path.basename(e)}`).join('\n')}
${infra.configs.map(c => `- Config: ${path.basename(c)}`).join('\n')}

## 🛡️ Governance Audit
- **Status**: ${audit.success ? '✅ PASSED' : '❌ FAILED'}
- **Rule Compliance**: ${sentinelRules.length - audit.violations.length}/${sentinelRules.length}
${audit.violations.slice(0, 3).map(v => `- Violation: [${v.ruleId}] in ${v.nodeId}`).join('\n')}

---
*Blueprint generated by the proprietary Conducks Graph engine.*
`;

    const outputPath = path.join(outputDir, 'BLUEPRINT.md');
    const llmsPath = path.join(outputDir, 'llms.txt');

    await fs.writeFile(outputPath, blueprint, 'utf-8');
    await fs.writeFile(llmsPath, blueprint, 'utf-8'); // For now, llms.txt is a copy of the blueprint

    return outputPath;
  }

  /**
   * Saves a blueprint snapshot as JSON to .conducks/blueprints/<pulseId>.json
   */
  public async saveSnapshot(pulseId: string, blueprint: object): Promise<void> {
    const snapshotsDir = path.join(process.cwd(), '.conducks', 'blueprints');
    await fs.mkdir(snapshotsDir, { recursive: true });
    const snapshotPath = path.join(snapshotsDir, `${pulseId}.json`);
    await fs.writeFile(snapshotPath, JSON.stringify(blueprint, null, 2), 'utf-8');
  }

  /**
   * Loads a blueprint snapshot.
   * ref can be a pulseId or a numeric offset like HEAD~3 (3rd most recent snapshot).
   */
  public async loadSnapshot(snapshotRef: string): Promise<object | null> {
    const snapshotsDir = path.join(process.cwd(), '.conducks', 'blueprints');

    const headMatch = snapshotRef.match(/^HEAD~(\d+)$/);
    if (headMatch) {
      const offset = parseInt(headMatch[1], 10);
      let files: string[];
      try {
        files = await fs.readdir(snapshotsDir);
      } catch {
        return null;
      }
      // Sort descending by filename (pulseIds are timestamps or sortable strings)
      const jsonFiles = files.filter(f => f.endsWith('.json')).sort().reverse();
      const target = jsonFiles[offset];
      if (!target) return null;
      snapshotRef = target.replace(/\.json$/, '');
    }

    const snapshotPath = path.join(snapshotsDir, `${snapshotRef}.json`);
    try {
      const raw = await fs.readFile(snapshotPath, 'utf-8');
      return JSON.parse(raw);
    } catch {
      return null;
    }
  }

  /**
   * Compares two blueprint snapshots and returns a structured diff.
   */
  public diffSnapshots(snapshotA: object, snapshotB: object): BlueprintDiff {
    const a = snapshotA as any;
    const b = snapshotB as any;

    const nodesA = new Set<string>(Array.isArray(a.nodes) ? a.nodes : []);
    const nodesB = new Set<string>(Array.isArray(b.nodes) ? b.nodes : []);
    const violationsA = new Set<string>(Array.isArray(a.rankViolations) ? a.rankViolations : []);
    const violationsB = new Set<string>(Array.isArray(b.rankViolations) ? b.rankViolations : []);
    const cyclesA: string[][] = Array.isArray(a.cycles) ? a.cycles : [];
    const cyclesB: string[][] = Array.isArray(b.cycles) ? b.cycles : [];

    const cycleKey = (c: string[]) => [...c].sort().join('|');
    const cycleSetA = new Set(cyclesA.map(cycleKey));
    const cycleSetB = new Set(cyclesB.map(cycleKey));

    return {
      nodesAdded: [...nodesB].filter(n => !nodesA.has(n)),
      nodesRemoved: [...nodesA].filter(n => !nodesB.has(n)),
      rankViolationsAdded: [...violationsB].filter(v => !violationsA.has(v)),
      rankViolationsRemoved: [...violationsA].filter(v => !violationsB.has(v)),
      newCycles: cyclesB.filter(c => !cycleSetA.has(cycleKey(c))),
      resolvedCycles: cyclesA.filter(c => !cycleSetB.has(cycleKey(c))),
    };
  }
}
