import fs from 'node:fs/promises';
import path from 'node:path';
import { ConducksAdjacencyList } from '../../core/graph/adjacency-list.js';
import { DAACClustering } from '../../core/algorithms/clustering/daac.js';
import { ConfigDetector } from './config-detector.js';
import { ConducksSentinel } from '../../core/policy/sentinel.js';

/**
 * Conducks — Blueprint (AI-Readiness Generator)
 * 
 * Generates a dense project manifest designed for Generative 
 * Engine Optimization (GEO). It allows other AIs to understand 
 * the project instantly.
 */
export class BlueprintGenerator {
  private daac = new DAACClustering();
  private detector = new ConfigDetector();
  private sentinel = new ConducksSentinel();

  /**
   * Generates a BLUEPRINT.md that summarizes the codebase 
   * based on the current graph and clusters.
   */
  public async generate(graph: ConducksAdjacencyList, outputDir: string = process.cwd()): Promise<string> {
    const clusterMap = this.daac.cluster(graph);
    const stats = graph.stats;
    
    // 1. Deep Discovery (Configs & Entry Points)
    const infra = await this.detector.discover(outputDir);
    
    // 2. Governance Audit
    const sentinelRules = JSON.parse(await fs.readFile(path.join(outputDir, 'sentinel.json'), 'utf-8').catch(() => '[]'));
    const audit = await this.sentinel.validate(graph, sentinelRules);

    // 3. Group by Clusters
    const clusters = new Map<string, string[]>();
    for (const [file, clusterId] of clusterMap.entries()) {
      if (!clusters.has(clusterId)) clusters.set(clusterId, []);
      clusters.get(clusterId)!.push(file);
    }

    let blueprint = `
# Conducks — Structural Graph Blueprint
This file provides a high-fidelity structural summary for AI agents and LLMs. 
Generated by the Conducks Graph on ${new Date().toLocaleString()}.

## 📊 Core Stats
- **Total Symbols (Nodes)**: ${stats.nodeCount}
- **Structural Relationships (Edges)**: ${stats.edgeCount}
- **Functional Modules**: ${clusters.size}

## 🏗️ Functional Architecture (DAAC Clusters)
The Conducks Graph has automatically categorized the following cohesive modules:

`;

    for (const [clusterId, files] of clusters.entries()) {
      const mainFiles = files.slice(0, 5).map(f => path.basename(f)).join(', ');
      blueprint += `### Module: ${clusterId}\n- **Core Files**: ${files.length} (${mainFiles}...)\n- **Context**: Structural cluster based on call-density and directory proximity.\n\n`;
    }

    blueprint += `
## 🚦 Entry Points & Config
Project root discovery found the following critical start points:
${infra.entries.map(e => `- Entry: ${path.basename(e)}`).join('\n')}
${infra.configs.map(c => `- Config: ${path.basename(c)}`).join('\n')}

## 🛡️ Governance Audit
- **Status**: ${audit.success ? '✅ PASSED' : '❌ FAILED'}
- **Rule Compliance**: ${sentinelRules.length - audit.violations.length}/${sentinelRules.length}
${audit.violations.slice(0, 3).map(v => `- Violation: [${v.ruleId}] in ${v.nodeId}`).join('\n')}

---
*Blueprint generated by the proprietary Conducks Graph engine.*
`;

    const outputPath = path.join(outputDir, 'BLUEPRINT.md');
    const llmsPath = path.join(outputDir, 'llms.txt');
    
    await fs.writeFile(outputPath, blueprint, 'utf-8');
    await fs.writeFile(llmsPath, blueprint, 'utf-8'); // For now, llms.txt is a copy of the blueprint
    
    return outputPath;
  }
}
